# Uncomment the next line to define a global platform for your project
# platform :ios, '12.1'

target 'PayMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for foursquare
  pod 'SnapKit', '~> 4.2'
  pod 'FirebaseDatabase', '~> 5.0'
  pod 'CodableFirebase', '~> 0.2'
end
